site_name: Vortex
theme: rtd-dropdown
docs_dir: ./rtfd
pages:
  - 'Introduction': index.md
  - 'Tutorial': tutorial.md
  - 'React Tutorial': react.md
  - 'Store Architecture': architecture/store.md
  - 'Index': reference/README.md
  - 'Classes':
    - 'Vortex': reference/classes/vortex.md
    - 'VortexContract': reference/classes/vortexcontract.md
  - 'Interfaces':
    - 'EmbarkContracts': reference/interfaces/embarkcontracts.md
    - 'TruffleContracts': reference/interfaces/trufflecontracts.md
    - 'ContractConfig': reference/interfaces/contractconfig.md
    - 'GeneratorConfig': reference/interfaces/generatorconfig.md
    - 'IPFSConfig': reference/interfaces/ipfsconfig.md
  - 'Enums':
    - 'FeedType': reference/enums/feedtype.md
  - 'States':
    - 'State': reference/interfaces/state.md
    - 'AccountConfigState': reference/interfaces/accountconfigstate.md
    - 'AccountErrorState': reference/interfaces/accounterrorstate.md
    - 'AccountInfoState': reference/interfaces/accountinfostate.md
    - 'AccountStoreState': reference/interfaces/accountstorestate.md
    - 'ContractAddressState': reference/interfaces/contractaddressesstate.md
    - 'ContractInstanceState': reference/interfaces/contractinstancestate.md
    - 'ContractStoreState': reference/interfaces/contractstorestate.md
    - 'ContractArtifactState': reference/interfaces/contractartifactstate.md
    - 'FeedNewAccountState': reference/interfaces/feednewaccountstate.md
    - 'FeedNewContractState': reference/interfaces/feednewcontractstate.md
    - 'FeedNewErrorState': reference/interfaces/feednewerrorstate.md
    - 'FeedNewErrorErrorState': reference/interfaces/feednewerrorerrorstate.md
    - 'FeedNewTransactionState': reference/interfaces/feednewtransactionstate.md
    - 'FeedNewIPFSContentState': reference/interfaces/feednewipfscontentstate.md
    - 'IPFSContentState': reference/interfaces/ipfscontentstate.md
    - 'IPFSErrorState': reference/interfaces/ipfserrorstate.md
    - 'IPFSStoreState': reference/interfaces/ipfsstorestate.md
    - 'IPFSConfigState': reference/interfaces/ipfsconfigstate.md
    - 'RawTransactionArgumentState': reference/interfaces/rawtransactionargumentstate.md
    - 'TransactionArgumentState': reference/interfaces/transactionargumentstate.md
    - 'TransactionBroadcastedState': reference/interfaces/transactionbroadcastedstate.md
    - 'TransactionConfirmedState': reference/interfaces/transactionconfirmedstate.md
    - 'TransactionErrorState': reference/interfaces/transactionerrorstate.md
    - 'TransactionReceiptState': reference/interfaces/transactionreceiptstate.md
    - 'TransactionState': reference/interfaces/transactionstate.md
    - 'TransactionStoreState': reference/interfaces/transactionstorestate.md
    - 'Web3LoadedState': reference/interfaces/web3loadedstate.md
    - 'Web3LoadErrorState': reference/interfaces/web3loaderrorstate.md
    - 'Web3LoadingState': reference/interfaces/web3loadingstate.md
    - 'Web3LockedState': reference/interfaces/web3lockedstate.md
    - 'Web3NetworkErrorState': reference/interfaces/web3networkerrorstate.md
