name: ethvtx CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install Yarn Globally
              run: npm install -g yarn@1.22.4
            - name: Install dependencies
              run: yarn install
            - name: Run TSLint
              run: yarn test:lint
            - name: Run Editorconfig
              run: yarn test:editorconfig
            - name: Run Mocha test suite
              run: yarn test:mocha
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
                parallel: true
                path-to-lcov: ./coverage/lcov.info
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
                parallel-finished: true



