name: ethvtx CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install dependencies
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - name: Run TSLint
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test:lint
            - name: Run Editorconfig
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test:editorconfig
            - name: Run Mocha test suite
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test:mocha
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
                parallel: true
                path-to-lcov: ./coverage/lcov.info
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
                parallel-finished: true



